name: Remote SSH Test

on:
  push:
    branches: [ main ]

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and run docker ps
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: docker ps
